### ISSUE TITLE
catch-all todo

### ISSUE THREAD

**Issue by BaseCase** [adorableio/version-one-shot#1]
- [ ] icons
- [x] make it only run on versionone and not everywhere
- [x] refactor story removal loop
- [ ] add a readme
- [ ] figure out how to make it installable
- [ ] listener that runs it whenever v1 tries to re-add the garbage (workaround exists in the `v` hotkey to re-execute.)

**Comment by bigtiger** [comment]
Addressed running everywhere in PR #2

**Comment by bigtiger** [comment]
Refactor story removal loop addressed in PR https://github.com/adorableio/version-one-shot/pull/3

**Comment by BaseCase** [comment]
Closing because we've split out the rest of the checklist items into their own issues.
